// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn9PseX8PNfpL5EISdN-ofaOBp7XeRw8k',
    appId: '1:328224950709:web:7b844047071b539e0531fc',
    messagingSenderId: '328224950709',
    projectId: 'mynotes-unique',
    authDomain: 'mynotes-unique.firebaseapp.com',
    storageBucket: 'mynotes-unique.appspot.com',
    measurementId: 'G-VQRWYP6F13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA680Eq18PLFlcySK73OKwBkoIAOtBSMAI',
    appId: '1:328224950709:android:28cdd917816784e60531fc',
    messagingSenderId: '328224950709',
    projectId: 'mynotes-unique',
    storageBucket: 'mynotes-unique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAns1hiCPxPMSvsMieP8kJXlIghJLhzBN0',
    appId: '1:328224950709:ios:0f4ec091bf4b96e40531fc',
    messagingSenderId: '328224950709',
    projectId: 'mynotes-unique',
    storageBucket: 'mynotes-unique.appspot.com',
    iosClientId: '328224950709-aad9jkoh573uoevk4nia6snbsngrkljg.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAns1hiCPxPMSvsMieP8kJXlIghJLhzBN0',
    appId: '1:328224950709:ios:0f4ec091bf4b96e40531fc',
    messagingSenderId: '328224950709',
    projectId: 'mynotes-unique',
    storageBucket: 'mynotes-unique.appspot.com',
    iosClientId: '328224950709-aad9jkoh573uoevk4nia6snbsngrkljg.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
